version: '3.8'

networks:
  network:
    driver: bridge
  shared_network:
    external: true

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trescudo-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./conf/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - network
      - shared_network
    environment:
      - TZ=UTC
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
